language: node_js
node_js:
  - 12.0.0
install:
  - npm install
script:
  - npm run test-services
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: ADD_API_KEY_HERE
  app:
    master: bot-prod